### ISSUE TITLE
Issue 2: Create Hero/Landing Page

### ISSUE THREAD

**Issue by deidaraiorek** [deidaraiorek/mimimeomeo#3]
### 📋 Description
Design and implement a hero/landing page for the app that includes a welcoming message, a brief description, and a call-to-action button (e.g., "Get Started"). This will be the first page users see when they visit the app.

### 🔍 Steps to Reproduce / Requirements
1. Create a new `Hero.js` file inside the `src/components/` folder.
2. Inside `Hero.js`, create a React functional component.
3. The component should return a section that includes:
   - A **welcoming headline** (e.g., "Welcome to Love Notes!").
   - A **short description** or tagline (e.g., "A place to store your special moments, images, and reminders.").
   - A **call-to-action button** (e.g., "Get Started") that leads to the notes page or another relevant section.
4. Style the hero section with Tailwind CSS to ensure it looks visually appealing:
   - Use a background image or gradient (`bg-gradient-to-r`, etc.).
   - Add padding and margins (`p-8`, `m-4`, etc.).
   - Center the content both vertically and horizontally (`flex`, `justify-center`, `items-center`).
5. Make the hero section **responsive** for mobile and desktop screens.

### 💡 Expected Behavior
The hero section should have a large welcoming message, a brief description of the app, and a call-to-action button. It should be styled nicely with Tailwind CSS and be responsive.

### ✅ Acceptance Criteria
- [ ] The hero section includes a headline, description, and call-to-action button.
- [ ] Tailwind CSS is used to style the hero section.
- [ ] The layout and design are responsive, working well on both mobile and desktop devices.

### 📚 Additional Context
Consider using a soft, pastel-themed color scheme to match the love-themed nature of the app. A subtle background image related to love, like hearts or soft clouds, could add a nice touch.

**Comment by ttrang87** [comment]
Resolve issue 2 hehe
